POST http://localhost:3001/api/login
Content-Type: application/json

{
    "email": "wearevet@gmail.com",
    "password": "llanetaJC05"
}


###refresh token

POST http://localhost:3001/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOlt7InBldF9vd25lcl9pZCI6MjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkcXJmUGxsNC9LRFpVMVBMZVBKVktSdVFyTTdLNXNIdVBYYktiOE16M3ZrOGFlMkVHTmQubi4iLCJuYW1lIjoiSmhheWNlZSBMbGFuZXRhIiwiYWRkcmVzcyI6IiIsImNvbnRhY3RfbnVtYmVyIjoiIn1dLCJpYXQiOjE2MTg2NDQyODF9.burDEQeprzXuBAdmp1Vd_pCG6ZopXoDfUKerah3kBJA"
}

###note: need refresh token to delete

DELETE http://localhost:3001/logout 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOlt7InBldF9vd25lcl9pZCI6MjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkcXJmUGxsNC9LRFpVMVBMZVBKVktSdVFyTTdLNXNIdVBYYktiOE16M3ZrOGFlMkVHTmQubi4iLCJuYW1lIjoiSmhheWNlZSBMbGFuZXRhIiwiYWRkcmVzcyI6IiIsImNvbnRhY3RfbnVtYmVyIjoiIn1dLCJpYXQiOjE2MTg2NDQyODF9.burDEQeprzXuBAdmp1Vd_pCG6ZopXoDfUKerah3kBJA"
}

###accesstoken
GET http://localhost:3001/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOlt7InZldF9hZG1pbl9pZCI6NiwiZW1haWwiOiJ3ZWFyZXZldEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRxcmZQbGw0L0tEWlUxUExlUEpWS1J1UXJNN0s1c0h1UFhiS2I4TXozdms4YWUyRUdOZC5uLiIsInZldF9uYW1lIjoiV2UgQXJlIFZldCAtIEFuaW1hbCBDbGluaWMiLCJ2ZXRfYWRkcmVzcyI6IjE2MzIgUCBQYXJlZGV6IE1hbGF0ZSwgTWFuaWxhIiwidmV0X2NvbnRhY3RfbnVtYmVyIjoiMDk0NzgxMjAzMzkiLCJ2ZXRfcGVybWl0IjoiIiwidmV0X3BpY3R1cmUiOiJodHRwOi8vbG9jYWxob3N0OjMwMDEvcHJvZmlsZS9wZXRvd25lci9wcm9maWxlX3BldG93bmVyXzE2MjA5MzMxMjg4NTAuanBnIiwidmV0X3N0YXR1cyI6IlBlbmRpbmcifV0sImlhdCI6MTYyMTEwOTIzNCwiZXhwIjoxNjIxMTk1NjM0fQ.uAYXY6qrl3yhe1HDEj61ka3jLQmwV2Q_B-nGFjjakvk